name: ModernalWorld
main: me.giverplay.MwRankup.Main
version: 1.5
commands:
  palito:
  rec:
  ping:
  reparar:
  falar:
  autosellall:
  traduzir:
  giverplay:
  warps:
  minas:
  kits:
  arenas:
  camarotes:
  habilitarplugin:
  desabilitarplugin:
  console:
  gsudo:
  op:
  cargo:
  mito:
  magnata:
  tpa:
  tpaceitar:
  tpnegar:
  tpadesativar:
  cash: